[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
favorites = "BktE7DHwEiypuR73GmY9LGBHtS7zkh9RYKvGoi9pM9oG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run jest --preset ts-jest"

[test]
startup_wait = 60